#include <stdio.h>
#include <vector>
#include <map>
#include <string>
#include <fstream>
#include <iostream>
#include <sstream>
#include <cstring>
#include <exception>
#include <time.h>
#include <typeinfo>
#include <cstdlib>
#include <cassert>
#include <stdexcept>
#include <sstream>
#include <typeinfo>
#include <algorithm>
#include <iomanip>
#include <exception>
#include <cstdint>
